//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountryTagHelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResCTH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResCTH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountryTagHelper.ResCTH", typeof(ResCTH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Arab Emirates.
        /// </summary>
        public static string AE {
            get {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        public static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua and Barbuda.
        /// </summary>
        public static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania.
        /// </summary>
        public static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angola.
        /// </summary>
        public static string AO {
            get {
                return ResourceManager.GetString("AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        public static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Samoa.
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria.
        /// </summary>
        public static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        public static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba.
        /// </summary>
        public static string AW {
            get {
                return ResourceManager.GetString("AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        public static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina.
        /// </summary>
        public static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbados.
        /// </summary>
        public static string BB {
            get {
                return ResourceManager.GetString("BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh.
        /// </summary>
        public static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium.
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkina Faso.
        /// </summary>
        public static string BF {
            get {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        public static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahrain.
        /// </summary>
        public static string BH {
            get {
                return ResourceManager.GetString("BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundi.
        /// </summary>
        public static string BI {
            get {
                return ResourceManager.GetString("BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benin.
        /// </summary>
        public static string BJ {
            get {
                return ResourceManager.GetString("BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bermuda.
        /// </summary>
        public static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei Darussalam.
        /// </summary>
        public static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivia.
        /// </summary>
        public static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        public static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamas, The.
        /// </summary>
        public static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutan.
        /// </summary>
        public static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        public static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize.
        /// </summary>
        public static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo, Dem. Rep..
        /// </summary>
        public static string CD {
            get {
                return ResourceManager.GetString("CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central African Republic.
        /// </summary>
        public static string CF {
            get {
                return ResourceManager.GetString("CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo, Rep..
        /// </summary>
        public static string CG {
            get {
                return ResourceManager.GetString("CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cote d&apos;Ivoire.
        /// </summary>
        public static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        public static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameroon.
        /// </summary>
        public static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        public static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica.
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuba.
        /// </summary>
        public static string CU {
            get {
                return ResourceManager.GetString("CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabo Verde.
        /// </summary>
        public static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curacao.
        /// </summary>
        public static string CW {
            get {
                return ResourceManager.GetString("CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus.
        /// </summary>
        public static string CY {
            get {
                return ResourceManager.GetString("CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        public static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djibouti.
        /// </summary>
        public static string DJ {
            get {
                return ResourceManager.GetString("DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominica.
        /// </summary>
        public static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        public static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria.
        /// </summary>
        public static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuador.
        /// </summary>
        public static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia.
        /// </summary>
        public static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt, Arab Rep..
        /// </summary>
        public static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eritrea.
        /// </summary>
        public static string ER {
            get {
                return ResourceManager.GetString("ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopia.
        /// </summary>
        public static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland.
        /// </summary>
        public static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji.
        /// </summary>
        public static string FJ {
            get {
                return ResourceManager.GetString("FJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micronesia, Fed. Sts..
        /// </summary>
        public static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        public static string FO {
            get {
                return ResourceManager.GetString("FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabon.
        /// </summary>
        public static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenada.
        /// </summary>
        public static string GD {
            get {
                return ResourceManager.GetString("GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        public static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghana.
        /// </summary>
        public static string GH {
            get {
                return ResourceManager.GetString("GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibraltar.
        /// </summary>
        public static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        public static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambia, The.
        /// </summary>
        public static string GM {
            get {
                return ResourceManager.GetString("GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea.
        /// </summary>
        public static string GN {
            get {
                return ResourceManager.GetString("GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equatorial Guinea.
        /// </summary>
        public static string GQ {
            get {
                return ResourceManager.GetString("GQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece.
        /// </summary>
        public static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        public static string GT {
            get {
                return ResourceManager.GetString("GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        public static string GU {
            get {
                return ResourceManager.GetString("GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea-Bissau.
        /// </summary>
        public static string GW {
            get {
                return ResourceManager.GetString("GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyana.
        /// </summary>
        public static string GY {
            get {
                return ResourceManager.GetString("GY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong SAR, China.
        /// </summary>
        public static string HK {
            get {
                return ResourceManager.GetString("HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras.
        /// </summary>
        public static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiti.
        /// </summary>
        public static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        public static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland.
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        public static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isle of Man.
        /// </summary>
        public static string IM {
            get {
                return ResourceManager.GetString("IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        public static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraq.
        /// </summary>
        public static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran, Islamic Rep..
        /// </summary>
        public static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Islands.
        /// </summary>
        public static string JG {
            get {
                return ResourceManager.GetString("JG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaica.
        /// </summary>
        public static string JM {
            get {
                return ResourceManager.GetString("JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordan.
        /// </summary>
        public static string JO {
            get {
                return ResourceManager.GetString("JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string JP {
            get {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenya.
        /// </summary>
        public static string KE {
            get {
                return ResourceManager.GetString("KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyz Republic.
        /// </summary>
        public static string KG {
            get {
                return ResourceManager.GetString("KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia.
        /// </summary>
        public static string KH {
            get {
                return ResourceManager.GetString("KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiribati.
        /// </summary>
        public static string KI {
            get {
                return ResourceManager.GetString("KI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comoros.
        /// </summary>
        public static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St. Kitts and Nevis.
        /// </summary>
        public static string KN {
            get {
                return ResourceManager.GetString("KN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea, Dem. People’s Rep..
        /// </summary>
        public static string KP {
            get {
                return ResourceManager.GetString("KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea, Rep..
        /// </summary>
        public static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwait.
        /// </summary>
        public static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cayman Islands.
        /// </summary>
        public static string KY {
            get {
                return ResourceManager.GetString("KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan.
        /// </summary>
        public static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao PDR.
        /// </summary>
        public static string LA {
            get {
                return ResourceManager.GetString("LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        public static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St. Lucia.
        /// </summary>
        public static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtenstein.
        /// </summary>
        public static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka.
        /// </summary>
        public static string LK {
            get {
                return ResourceManager.GetString("LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberia.
        /// </summary>
        public static string LR {
            get {
                return ResourceManager.GetString("LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesotho.
        /// </summary>
        public static string LS {
            get {
                return ResourceManager.GetString("LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuania.
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg.
        /// </summary>
        public static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia.
        /// </summary>
        public static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libya.
        /// </summary>
        public static string LY {
            get {
                return ResourceManager.GetString("LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        public static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco.
        /// </summary>
        public static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldova.
        /// </summary>
        public static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro.
        /// </summary>
        public static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St. Martin (French part).
        /// </summary>
        public static string MF {
            get {
                return ResourceManager.GetString("MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madagascar.
        /// </summary>
        public static string MG {
            get {
                return ResourceManager.GetString("MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshall Islands.
        /// </summary>
        public static string MH {
            get {
                return ResourceManager.GetString("MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia, FYR.
        /// </summary>
        public static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mali.
        /// </summary>
        public static string ML {
            get {
                return ResourceManager.GetString("ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar.
        /// </summary>
        public static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolia.
        /// </summary>
        public static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macao SAR, China.
        /// </summary>
        public static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northern Mariana Islands.
        /// </summary>
        public static string MP {
            get {
                return ResourceManager.GetString("MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritania.
        /// </summary>
        public static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malta.
        /// </summary>
        public static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritius.
        /// </summary>
        public static string MU {
            get {
                return ResourceManager.GetString("MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives.
        /// </summary>
        public static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawi.
        /// </summary>
        public static string MW {
            get {
                return ResourceManager.GetString("MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        public static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        public static string MY {
            get {
                return ResourceManager.GetString("MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambique.
        /// </summary>
        public static string MZ {
            get {
                return ResourceManager.GetString("MZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Caledonia.
        /// </summary>
        public static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niger.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria.
        /// </summary>
        public static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua.
        /// </summary>
        public static string NI {
            get {
                return ResourceManager.GetString("NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands.
        /// </summary>
        public static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepal.
        /// </summary>
        public static string NP {
            get {
                return ResourceManager.GetString("NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauru.
        /// </summary>
        public static string NR {
            get {
                return ResourceManager.GetString("NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        public static string NZ {
            get {
                return ResourceManager.GetString("NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oman.
        /// </summary>
        public static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama.
        /// </summary>
        public static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        public static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Polynesia.
        /// </summary>
        public static string PF {
            get {
                return ResourceManager.GetString("PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papua New Guinea.
        /// </summary>
        public static string PG {
            get {
                return ResourceManager.GetString("PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        public static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        public static string PK {
            get {
                return ResourceManager.GetString("PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Rico.
        /// </summary>
        public static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Bank and Gaza.
        /// </summary>
        public static string PS {
            get {
                return ResourceManager.GetString("PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palau.
        /// </summary>
        public static string PW {
            get {
                return ResourceManager.GetString("PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguay.
        /// </summary>
        public static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar.
        /// </summary>
        public static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbia.
        /// </summary>
        public static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Federation.
        /// </summary>
        public static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda.
        /// </summary>
        public static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabia.
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solomon Islands.
        /// </summary>
        public static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychelles.
        /// </summary>
        public static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudan.
        /// </summary>
        public static string SD {
            get {
                return ResourceManager.GetString("SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        public static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak Republic.
        /// </summary>
        public static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone.
        /// </summary>
        public static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to San Marino.
        /// </summary>
        public static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegal.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somalia.
        /// </summary>
        public static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suriname.
        /// </summary>
        public static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Sudan.
        /// </summary>
        public static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tome and Principe.
        /// </summary>
        public static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador.
        /// </summary>
        public static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sint Maarten (Dutch part).
        /// </summary>
        public static string SX {
            get {
                return ResourceManager.GetString("SX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrian Arab Republic.
        /// </summary>
        public static string SY {
            get {
                return ResourceManager.GetString("SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaziland.
        /// </summary>
        public static string SZ {
            get {
                return ResourceManager.GetString("SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turks and Caicos Islands.
        /// </summary>
        public static string TC {
            get {
                return ResourceManager.GetString("TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chad.
        /// </summary>
        public static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Togo.
        /// </summary>
        public static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        public static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistan.
        /// </summary>
        public static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timor-Leste.
        /// </summary>
        public static string TL {
            get {
                return ResourceManager.GetString("TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan.
        /// </summary>
        public static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisia.
        /// </summary>
        public static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonga.
        /// </summary>
        public static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidad and Tobago.
        /// </summary>
        public static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuvalu.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan, China.
        /// </summary>
        public static string TW {
            get {
                return ResourceManager.GetString("TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzania.
        /// </summary>
        public static string TZ {
            get {
                return ResourceManager.GetString("TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        public static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uganda.
        /// </summary>
        public static string UG {
            get {
                return ResourceManager.GetString("UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguay.
        /// </summary>
        public static string UY {
            get {
                return ResourceManager.GetString("UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        public static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St. Vincent and the Grenadines.
        /// </summary>
        public static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela, RB.
        /// </summary>
        public static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Virgin Islands.
        /// </summary>
        public static string VG {
            get {
                return ResourceManager.GetString("VG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgin Islands (U.S.).
        /// </summary>
        public static string VI {
            get {
                return ResourceManager.GetString("VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam.
        /// </summary>
        public static string VN {
            get {
                return ResourceManager.GetString("VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanuatu.
        /// </summary>
        public static string VU {
            get {
                return ResourceManager.GetString("VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa.
        /// </summary>
        public static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosovo.
        /// </summary>
        public static string XK {
            get {
                return ResourceManager.GetString("XK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemen, Rep..
        /// </summary>
        public static string YE {
            get {
                return ResourceManager.GetString("YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        public static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambia.
        /// </summary>
        public static string ZM {
            get {
                return ResourceManager.GetString("ZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwe.
        /// </summary>
        public static string ZW {
            get {
                return ResourceManager.GetString("ZW", resourceCulture);
            }
        }
    }
}
